server:
  port: 8085

notificacion:
  webhook:
    estado-envio:
      url: http://local1
    confirmacion-orden:
      url: https://n8nworkflows1.app.n8n.cloud/webhook-test/a3b0c2ff-c479-4efd-9613-d31583a70b8a

spring:
  application:
      name: orden-service
  config:
      import: optional:configserver:http://localhost:8888
  profiles:
      active: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: arka
    password: arka123
