server:
  port: 8085

notificacion:
  webhook:
    estado-envio:
      url: http://local1
    confirmacion-orden:
      url: http://local2
spring:
  application:
    name: orden-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: arka
    password: arka123
